### ISSUE TITLE
[배경] 무드 개선 및 배경 컨셉 재구성

### ISSUE THREAD

**Issue by emazine** [AvocadoSandwich/HellFurnaceIssue#5]
![image](https://user-images.githubusercontent.com/87243116/178432226-885680c9-6696-4ad5-b228-14bd71b54d2a.png)
![image](https://user-images.githubusercontent.com/87243116/178437697-11812305-e484-471c-8cf6-68828a50aa2e.png)

- 검토중인 무드 : 레드 - 청록화이트 계열
- 검토 사유 : 색의 균형이 붉은 쪽으로 많이 쏠려 있어서 빨강의 보색인 청록색을 엠비언트로 잡아볼 예정

> - 대체적으로 주인공은 푸른~흰 계열, 배경과 적들은 붉은 계열로 구성
> - 아래에서 위로 빨간 라이트(자연조명, 용암), 위에서 아래로는 화이트 라이트(인공조명), 엠비언트는 옅은 초록 계열
> - 근경과 배경 렙디는 사이드뷰에서 봤을 땐 어두운 청록 계열로 보이게끔 함, 따라서 붉은 계열의 배경과 분리되게 만든다
> - 이외의 색감(파랑,노랑 등)은 플레이어의 무기와 무기 이펙트 쪽에서만 다룬다

- 기존 무드

![image](https://user-images.githubusercontent.com/87243116/178433001-277e442f-cc36-43dc-b43f-8d5987c2697a.png)

핑크-옐로우화이트 계열

**Comment by emazine** [comment]
무드 R&D 시도중...어렵네요
---
![image](https://user-images.githubusercontent.com/87243116/178558872-6d4cdc3a-0c9f-49bb-a65e-0f8826cd7476.png)
왼쪽이 현재 검토중인 무드의 시안입니다 형태가 뭉개지더라도 무드를 빠르게 확인하기 위해 계속 덮어서 그리는 중입니다!

- 가독성을 좀더 챙겨야 할 것 같아요
- 분위기가 너무 어두워지지 않도록 조심해야 할 것 같아요..
- 안개가 좀 많이 껴있어서 어느정도 걷어내줘야 할 것 같아요 게임이 답답해보일 수 있겠어요

계속 R&D 중이어서 이대로 바로 확정은 아닙니다! 피드백 있으신 경우 댓글로 남겨주시면 감사드리겠습니다!

**Comment by biru100** [comment]
이펙트가 더 강조될 수 있는 배경 구성이었으면 좋겠습니다. (Ex. 플레이어 동선의 명도를 낮게)

**Comment by emazine** [comment]
![image](https://user-images.githubusercontent.com/87243116/178571151-71d7c1f8-45c8-4d10-b30d-54bfa0d67aa6.png)
명규님의 무드 제안
명규님 : 아래에서 올라오는 용암 라이트를 완전한 붉은 색으로 만들면 이펙트가 강조될 수 있을 것 같음.

- 명규님의 제안 반응 정리 : 장기간 플레이하기에는 눈이 아프고 무드가 무겁다는 점이 있어서, 일반보다는 보스전에서 활용해보면 좋을 것 같아요!
